### ISSUE TITLE
fbneo_libretro.wasm 中没有设置宽高比的方法吗？

### ISSUE THREAD

**Issue by rexhang** [nenge123/emulatorjs#10]
### 我想知道游戏核心是否提供了渲染比例或填充画布容器的宽度和高度的选项？

![image](https://github.com/nenge123/emulatorjs/assets/14832793/94055163-7485-4d86-aeff-5effc786d770)

如上图所示，画布的宽度和高度设置为200:120，但是渲染出来的游戏画面只有4:3，并且画布容器没有被覆盖。核心是否提供了改变渲染比例的方法？

![image](https://github.com/nenge123/emulatorjs/assets/14832793/d049cc11-10a7-4ab2-82a3-170fc3407b6c)

在Module对象中没有找到对应的方法

希望您能给我答复，非常感谢。

**Comment by nenge123** [comment]
首先设置画布css 如手机竖屏时 width:100% !important;height:auto !important; 横屏时反过来。
但是你也可以设置特定宽。


强制修改，找到Module.callMain
下一行加入Module.setCanvans(width,height)
如160x5，140x5注意纵横比，值越大越清晰

智能方式，具体你要看控制台输出“video 160x140”这种关键字。
查找Module =
然后往下找到printErr(text)
增加语录判断
if(/vidoe\s\d+x\d+/.test(text)){
var wh = (text.match (vidoe\s*(\d+x\d+)))[1].split('x');
wh = wh[0]/wh[1];
Module.setCanvans(720,720/wh);
最好把wh值保存下來 如Module.wh=wh
}


如果在ejs里面，还需要进一步修改
查找 setCanvans
你就会发现它在callMain后其实调整了纵横比，
因此你可以选择删掉所有setCanvans

也可以在局部函数里面语句最后加上，推荐

Module.setCanvans(720,720/Module.wh);
因为它有resize事件，

**Comment by nenge123** [comment]
打错了，是这个
setCanvasSize

**Comment by nenge123** [comment]
设置里面的宽高相当于分辨率，越大越清晰（像素），越小越模糊。
而设置画布css，要用important ，相当于你的显示屏多少寸
显示屏纵横比要和分辨率一致，否则畸形画面

**Comment by rexhang** [comment]
![image](https://github.com/nenge123/emulatorjs/assets/14832793/13e927e1-4cf4-4872-a8ff-7a5476c205cf)

![image](https://github.com/nenge123/emulatorjs/assets/14832793/0ead01d3-33f7-4c0e-a0a7-a7fdc1b7862c)

**Comment by rexhang** [comment]
> ![image](https://user-images.githubusercontent.com/14832793/264265415-13e927e1-4cf4-4872-a8ff-7a5476c205cf.png)
> 
> ![image](https://user-images.githubusercontent.com/14832793/264265495-0ead01d3-33f7-4c0e-a0a7-a7fdc1b7862c.png)

最终是去调用 `updateCanvasDimensions`

updateCanvasDimensions

**Comment by rexhang** [comment]
> > ![image](https://user-images.githubusercontent.com/14832793/264265415-13e927e1-4cf4-4872-a8ff-7a5476c205cf.png)
> > ![image](https://user-images.githubusercontent.com/14832793/264265495-0ead01d3-33f7-4c0e-a0a7-a7fdc1b7862c.png)
> 
> 最终是去调用 `updateCanvasDimensions`
> 
> updateCanvasDimensions

![image](https://github.com/nenge123/emulatorjs/assets/14832793/64c328d1-8bf8-47b7-a287-3fb39ebf9ddc)

![image](https://github.com/nenge123/emulatorjs/assets/14832793/853d6004-935e-49f8-806c-132d31685769)

**Comment by rexhang** [comment]
这里没有对游戏画面的比例进行调整 调整的只是canvas的宽高

![image](https://github.com/nenge123/emulatorjs/assets/14832793/99685583-89f0-4862-bb05-38cb9f127820)

**Comment by rexhang** [comment]
![image](https://github.com/nenge123/emulatorjs/assets/14832793/f4045597-eda0-48ca-88b0-aa3a936dc1b9)

**Comment by rexhang** [comment]
> ![image](https://user-images.githubusercontent.com/14832793/264273979-f4045597-eda0-48ca-88b0-aa3a936dc1b9.png)

抓取到相关信息，然后查看调用堆栈，没有找到关于视频 video size 的设置

**Comment by rexhang** [comment]
最终尝试了下，只能够修改canvas尺寸信息，无法修改渲染范围(例如铺满整个canvas 从0,0 到 canvas.width, canvas.height)

**Comment by nenge123** [comment]
感觉你喺度语无伦次。怎么就没填满了？
还有就是我给你的是例子，你控制台给你的是800多，而你缩放720其实是在放小。

控制台给你的是游戏分辨率，Html画布（canvan）。

保持纵横比全屏情况下，那么游戏就会填满画布的每一格，如果画布宽多了10像素，那么显示结果是图像左右有5像素黑边。

如果不保持纵横比满屏幕情况下，一但纵横比相差太大，就是畸形画面。

…………

还有css方面，当网页宽远远大于高时。自适应情况下，画布应该高与网页一致，而两侧会有画布与网页两侧黑边，这是你所谓的没填满？？？
你想这个填满很简单，把画布width从auto设置100%即可！

**Comment by nenge123** [comment]
你要验证自己问题很简单，给画布设置背景色红色，给id=game 设置白边。看到红是画布没填满，看到白边是画布没占满网页屏幕

**Comment by nenge123** [comment]
這個比例是設置html 實現。



![image](https://github.com/nenge123/emulatorjs/assets/16117315/b00def6c-b99f-437d-939f-f84861024172)![image](https://github.com/nenge123/emulatorjs/assets/16117315/7120f696-6e96-404a-b685-4aea405dd789)
![image](https://github.com/nenge123/emulatorjs/assets/16117315/44734c7a-3cae-4282-9909-c48cfaff0676)

**Comment by rexhang** [comment]
![image](https://github.com/nenge123/emulatorjs/assets/14832793/bacfeef1-59cf-4347-b0a7-4df085ebfec9)

我给canvas设置了背景 但是游戏在里面还是没渲染满

**Comment by rexhang** [comment]
> 這個比例是設置html 實現。
> 
> ![image](https://user-images.githubusercontent.com/16117315/264314607-b00def6c-b99f-437d-939f-f84861024172.jpeg)![image](https://user-images.githubusercontent.com/16117315/264314608-7120f696-6e96-404a-b685-4aea405dd789.jpeg) ![image](https://user-images.githubusercontent.com/16117315/264314722-44734c7a-3cae-4282-9909-c48cfaff0676.jpeg)

你的是可以的
