### ISSUE TITLE
Is there any option to update retroarch cores?

### ISSUE THREAD

**Issue by shaylevary** [nenge123/emulatorjs#12]
Hi,

Since this great project has been abandoned, I would like to ask please if there is any option to update the latest retroarch cores while using the latest decoded emulatorjs v5.8 ?

Thank you.

**Comment by nenge123** [comment]
latest retroarch[emulatorjs] cores have a time hash ,so you may can't start.
the lastest cores not have `_gettimeofday` function ,`It obtains the current time very covertly`
