### ISSUE TITLE
releases里下载的emulator.js和e.min.js并不是同样代码

### ISSUE THREAD

**Issue by xq4894253** [nenge123/emulatorjs#2]
releases里下载的e.min.js并不是单独提供的emulator.js文件压缩后的代码，想进一步修改无法进行，能提供一下正确的源码js文件吗大佬

**Comment by nenge123** [comment]
这已经是解密后的版本。不信你去他网站看看原版2MB非压缩的大小。

怎么修改？其实他就两个主要的一个函数，从底部往上看那个。利用console.log探索吧，不要说不行。


另外e.min.js是魔改过的版本，例如indexdb使用方式被我替换了，ajax被我变成fetch，启动方式也有改动。由于前期很多东西非标准不建议使用。
