### ISSUE TITLE
FBneo GamePad 不能匹配按键啊

### ISSUE THREAD

**Issue by rexhang** [nenge123/emulatorjs#7]

**Comment by nenge123** [comment]
fbneo不属于默认核心，需要根据json配置文件修改吧

**Comment by rexhang** [comment]
> fbneo不属于默认核心，需要根据json配置文件修改吧

意思 要适配 fbneo 需要手动修改gamepad的配置文件么？

**Comment by nenge123** [comment]
gamepad是手柄js事件适配，一般以ps手柄为准。国产手柄并不担保正确自动映射。


---

如果触摸按钮映射错误，参考如下。
你用那个版本，还是单独核心？

单独核心：他的按键配置在fbneo.json 参考里面的buttons，大概能看见按键映射。

如果你用0.4.99你要确保fbneo.json已经加载。

0.5.8我只是解码，和替换indexedb的处理方式，并没有加大力度replace

如果真有gamepad问题，可以尝试从原始解码中把他原来的gamepad模块提取出来。

**Comment by nenge123** [comment]
代码建议慢慢探索吧，里面有原始解码，和修改后的解码，可以对照修改。

0.5.8模拟核心，时间密匙方面基本上已经破解了（替换函数，使得时间检测固定），所以无需连接emulatorjs获取时间密匙。但是mame方面仍需要连接，判断rom名

**Comment by rexhang** [comment]
> 代码建议慢慢探索吧，里面有原始解码，和修改后的解码，可以对照修改。
> 
> 0.5.8模拟核心，时间密匙方面基本上已经破解了（替换函数，使得时间检测固定），所以无需连接emulatorjs获取时间密匙。但是mame方面仍需要连接，判断rom名

感谢回复, 我参考下。

**Comment by rexhang** [comment]
@nenge123 [这个网站](https://play.wo1wan.com) 是用的什么技术，是开源的底层库吗？

**Comment by nenge123** [comment]
在线游戏？微信小程序并不支持C，所以不可能是C。因此应该是HTML5，然后利用微信开放接口注册用户。保留用户信息。

什么技术？别人是小公司，懂吗？
你会C也能弄，就是下载模拟器的C源代码，编译成asm。就可以在浏览器运行了

**Comment by nenge123** [comment]
如果仍有手柄映射问题直接用0.5.14原版 ,已经测试测试好
