### ISSUE TITLE
近两日开始报错

### ISSUE THREAD

**Issue by xq4894253** [nenge123/emulatorjs#8]
测试GBA/NES/SNES游戏全都报"memory access out of bounds"内存访问越界

**Comment by xq4894253** [comment]
没注意到有0.5.8版本，我再看看

**Comment by nenge123** [comment]
这个是没有分配默认内存问题。
Module.TOTAL_MEMORY ，一般设置最大值0x10000000

**Comment by rexhang** [comment]
> 这个是没有分配默认内存问题。 Module.TOTAL_MEMORY ，一般设置最大值0x10000000

0x10000000 不就是 0 么

**Comment by rexhang** [comment]
我也是同样的问题，运行的时候，这里的值变成 Module.TOTAL_MEMORY = 0了，正常打印Module.TOTAL_MEMORY = 268435456 才对

core: arcade

![image](https://github.com/nenge123/emulatorjs/assets/14832793/721a6beb-3065-4fb8-aa0d-18bff7f78f45)

怎么解决呢
