### ISSUE TITLE
Why not use webgl2 to build?

### ISSUE THREAD

**Issue by rexhang** [nenge123/emulatorjs#9]
Others' websites use webgl2 for rendering, which has better performance, smoother operation, and lower hardware usage, Also supports high frame rate.

![image](https://github.com/nenge123/emulatorjs/assets/14832793/d7e8c573-358a-4117-9a0c-ad2df00b9de5)

And our canvas currently uses webgl to render instead of webgl2.

![image](https://github.com/nenge123/emulatorjs/assets/14832793/cdb405f8-0339-4bf7-8843-1def9731b0ab)

Here to upgrade the rendering method to webgl2, is it necessary to re-make C language make to wasm files?

Hope to get your reply support.

thanks.

**Comment by nenge123** [comment]
you can replace '"webgl"' to '"webgl2"' in retroarch.js .than will webgl2

**Comment by nenge123** [comment]
![image](https://github.com/nenge123/emulatorjs/assets/16117315/e80673de-6fb8-47cf-bf7c-06aa5fdb69c0)

**Comment by rexhang** [comment]
> ![image](https://user-images.githubusercontent.com/16117315/263598163-e80673de-6fb8-47cf-bf7c-06aa5fdb69c0.jpeg)

How did you do it？

**Comment by nenge123** [comment]
replace js
if u use .4.99.  find "wasmAsmjs"
add at the end wasmAsmjs = wasmAsmjs.replace('"webgl"','"webgl2"')

0.5.8
find 'WASM_JS'


WASM_JS = WASM_JS.replace('"webgl"','"webgl2"')

if use arcade-data.zip
unfile , replace the "retroarch.js"

**Comment by rexhang** [comment]
> replace js if u use .4.99. find "wasmAsmjs" add at the end wasmAsmjs = wasmAsmjs.replace('"webgl"','"webgl2"')
> 
> 0.5.8 find 'WASM_JS'
> 
> WASM_JS = WASM_JS.replace('"webgl"','"webgl2"')
> 
> if use arcade-data.zip unfile , replace the "retroarch.js"

how to run arcade games? visit /arcade.html ?

**Comment by nenge123** [comment]
arcade.html is test to run，u must edit index.html to run arcade

**Comment by rexhang** [comment]
> arcade.html is test to run，u must edit index.html to run arcade

arcade game seems to need url to load file or blobObject can't

**Comment by nenge123** [comment]
<script type="text/javascript">
        var EJS_DEBUG_ = true;
        var EJS_EMU = new EJS('#game',{
            gameUrl:'kof97.zip',
            system:'arcade',
            biosurl:'bios/arcade.7z', //set bios
        });
    </script>
</body>
</html>

**Comment by rexhang** [comment]
> 'bios/arcade.7z'

Error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')

**Comment by nenge123** [comment]
I'm sorry, I ignored the capitalisation, which led to an error.

**Comment by nenge123** [comment]
<script type="text/javascript">
    var EJS_DEBUG_ = true;
    var EJS_EMU = new EJS('#game',{
        gameUrl:'kof97.zip',
        system:'arcade',
        biosUrl:'bios/arcade.7z',
        gameParentUrl:[],
    });
</script>

**Comment by rexhang** [comment]
![image](https://github.com/nenge123/emulatorjs/assets/14832793/917fb7e2-df53-467f-ad74-b51b49f15a3e)

Upgraded to webgl2 

Thank you.

**Comment by nenge123** [comment]
Can webgl2 reduce the power consumption of mobile phones?

l using the steamdeck，so it is longtime not use web play in iphone

**Comment by rexhang** [comment]
> Can webgl2 reduce the power consumption of mobile phones?
> 
> l using the steamdeck，so it is longtime not use web play in iphone

Judging from my current performance data, no conclusion can be reached yet. It seems that it is only backward compatible, maybe it needs to change the calling API or something else?
